name: Update Pride XML

on:
  schedule:
    - cron: "0 */2 * * *"   # кожні 2 години
  workflow_dispatch:        # можна запускати вручну

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests

      - name: Run fixer script
        run: python fix_pride.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/prideMotoChina_fixed.xml
            git commit -m "Update prideMotoChina_fixed.xml"
            git push
          else:
            echo "Немає змін, коміт не потрібен."
          fi
